import mysql.connector
from fyers_apiv3 import fyersModel
import pandas as pd
import os
import pandas as pd
import plotly.graph_objects as go
import datetime as dt
from datetime import timedelta, datetime
from fyers_apiv3.FyersWebsocket import data_ws
with open("abcd.txt", 'r') as r:
    access_token = r.read()
client_id = "DZO41L3M36-100"
fyers = fyersModel.FyersModel(
    client_id=client_id, is_async=False, token=access_token, log_path=os.getcwd())
fyers.get_profile()

lines = [
    'NSE:360ONE-EQ',
    'NSE:3MINDIA-EQ',
    'NSE:AARTIIND-EQ',
    'NSE:AAVAS-EQ',
    'NSE:ABB-EQ',
    'NSE:ABBOTINDIA-EQ',
    'NSE:ABCAPITAL-EQ',
    'NSE:ABFRL-EQ',
    'NSE:ACC-EQ',
    'NSE:ACE-EQ',
    'NSE:ACI-EQ',
    'NSE:ADANIENSOL-EQ',
    'NSE:ADANIENT-EQ',
    'NSE:ADANIGREEN-EQ',
    'NSE:ADANIPORTS-EQ',
    'NSE:ADANIPOWER-EQ',
    'NSE:AEGISLOG-EQ',
    'NSE:AETHER-EQ',
    'NSE:AFFLE-EQ',
    'NSE:AIAENG-EQ',
    'NSE:AJANTPHARM-EQ',
    'NSE:ALKEM-EQ',
    'NSE:ALKYLAMINE-EQ',
    'NSE:ALLCARGO-EQ',
    'NSE:ALOKINDS-EQ',
    'NSE:AMBER-EQ',
    'NSE:AMBUJACEM-EQ',
    'NSE:ANANDRATHI-EQ',
    'NSE:ANGELONE-EQ',
    'NSE:ANURAS-EQ',
    'NSE:APARINDS-EQ',
    'NSE:APLAPOLLO-EQ',
    'NSE:APLLTD-EQ',
    'NSE:APOLLOHOSP-EQ',
    'NSE:APOLLOTYRE-EQ',
    'NSE:APTUS-EQ',
    'NSE:ARE-M-EQ',
    'NSE:ASAHIINDIA-EQ',
    'NSE:ASHOKLEY-EQ',
    'NSE:ASIANPAINT-EQ',
    'NSE:ASTERDM-EQ',
    'NSE:ASTRAL-EQ',
    'NSE:ASTRAZEN-EQ',
    'NSE:ATGL-EQ',
    'NSE:ATUL-EQ',
    'NSE:AUBANK-EQ',
    'NSE:AUROPHARMA-EQ',
    'NSE:AVANTIFEED-EQ',
    'NSE:AWL-EQ',
    'NSE:AXISBANK-EQ',
    'NSE:BAJAJ-AUTO-EQ',
    'NSE:BAJAJFINSV-EQ',
    'NSE:BAJAJHLDNG-EQ',
    'NSE:BAJFINANCE-EQ',
    'NSE:BALAMINES-EQ',
    'NSE:BALKRISIND-EQ',
    'NSE:BALRAMCHIN-EQ',
    'NSE:BANDHANBNK-EQ',
    'NSE:BANKBARODA-EQ',
    'NSE:BANKINDIA-EQ',
    'NSE:BATAINDIA-EQ',
    'NSE:BAYERCROP-EQ',
    'NSE:BBTC-EQ',
    'NSE:BDL-EQ',
    'NSE:BEL-EQ',
    'NSE:BEML-EQ',
    'NSE:BERGEPAINT-EQ',
    'NSE:BHARATFORG-EQ',
    'NSE:BHARTIARTL-EQ',
    'NSE:BHEL-EQ',
    'NSE:BIKAJI-EQ',
    'NSE:BIOCON-EQ',
    'NSE:BIRLACORPN-EQ',
    'NSE:BLS-EQ',
    'NSE:BLUEDART-EQ',
    'NSE:BLUESTARCO-EQ',
    'NSE:BORORENEW-EQ',
    'NSE:BOSCHLTD-EQ',
    'NSE:BPCL-EQ',
    'NSE:BRIGADE-EQ',
    'NSE:BRITANNIA-EQ',
    'NSE:BSE-EQ',
    'NSE:BSOFT-EQ',
    'NSE:CAMPUS-EQ',
    'NSE:CAMS-EQ',
    'NSE:CANBK-EQ',
    'NSE:CANFINHOME-EQ',
    'NSE:CAPLIPOINT-EQ',
    'NSE:CARBORUNIV-EQ',
    'NSE:CASTROLIND-EQ',
    'NSE:CCL-EQ',
    'NSE:CDSL-EQ',
    'NSE:CEATLTD-EQ',
    'NSE:CELLO-EQ',
    'NSE:CENTRALBK-EQ',
    'NSE:CENTURYPLY-EQ',
    'NSE:CENTURYTEX-EQ',
    'NSE:CERA-EQ',
    'NSE:CESC-EQ',
    'NSE:CGCL-EQ',
    'NSE:CGPOWER-EQ',
    'NSE:CHALET-EQ',
    'NSE:CHAMBLFERT-EQ',
    'NSE:CHEMPLASTS-EQ',
    'NSE:CHENNPETRO-EQ',
    'NSE:CHOLAFIN-EQ',
    'NSE:CHOLAHLDNG-EQ',
    'NSE:CIEINDIA-EQ',
    'NSE:CIPLA-EQ',
    'NSE:CLEAN-EQ',
    'NSE:COALINDIA-EQ',
    'NSE:COCHINSHIP-EQ',
    'NSE:COFORGE-EQ',
    'NSE:COLPAL-EQ',
    'NSE:CONCOR-EQ',
    'NSE:CONCORDBIO-EQ',
    'NSE:COROMANDEL-EQ',
    'NSE:CRAFTSMAN-EQ',
    'NSE:CREDITACC-EQ',
    'NSE:CRISIL-EQ',
    'NSE:CROMPTON-EQ',
    'NSE:CSBBANK-EQ',
    'NSE:CUB-EQ',
    'NSE:CUMMINSIND-EQ',
    'NSE:CYIENT-EQ',
    'NSE:DABUR-EQ',
    'NSE:DALBHARAT-EQ',
    'NSE:DATAPATTNS-EQ',
    'NSE:DCMSHRIRAM-EQ',
    'NSE:DEEPAKFERT-EQ',
    'NSE:DEEPAKNTR-EQ',
    'NSE:DELHIVERY-EQ',
    'NSE:DEVYANI-EQ',
    'NSE:DIVISLAB-EQ',
    'NSE:DIXON-EQ',
    'NSE:DLF-EQ',
    'NSE:DMART-EQ',
    'NSE:DOMS-EQ',
    'NSE:DRREDDY-EQ',
    'NSE:EASEMYTRIP-EQ',
    'NSE:EICHERMOT-EQ',
    'NSE:EIDPARRY-EQ',
    'NSE:EIHOTEL-EQ',
    'NSE:ELECON-EQ',
    'NSE:ELGIEQUIP-EQ',
    'NSE:EMAMILTD-EQ',
    'NSE:ENDURANCE-EQ',
    'NSE:ENGINERSIN-EQ',
    'NSE:EPL-EQ',
    'NSE:EQUITASBNK-EQ',
    'NSE:ERIS-EQ',
    'NSE:ESCORTS-EQ',
    'NSE:EXIDEIND-EQ',
    'NSE:FACT-EQ',
    'NSE:FDC-EQ',
    'NSE:FEDERALBNK-EQ',
    'NSE:FINCABLES-EQ',
    'NSE:FINEORG-EQ',
    'NSE:FINNIFTY-INDEX',
    'NSE:FINPIPE-EQ',
    'NSE:FIVESTAR-EQ',
    'NSE:FLUOROCHEM-EQ',
    'NSE:FORTIS-EQ',
    'NSE:FSL-EQ',
    'NSE:GAEL-EQ',
    'NSE:GAIL-EQ',
    'NSE:GESHIP-EQ',
    'NSE:GICRE-EQ',
    'NSE:GILLETTE-EQ',
    'NSE:GLAND-EQ',
    'NSE:GLAXO-EQ',
    'NSE:GLENMARK-EQ',
    'NSE:GLS-EQ',
    'NSE:GMDCLTD-EQ',
    'NSE:GMMPFAUDLR-EQ',
    'NSE:GMRINFRA-EQ',
    'NSE:GNFC-EQ',
    'NSE:GODFRYPHLP-EQ',
    'NSE:GODREJCP-EQ',
    'NSE:GODREJIND-EQ',
    'NSE:GODREJPROP-EQ',
    'NSE:GPIL-EQ',
    'NSE:GPPL-EQ',
    'NSE:GRANULES-EQ',
    'NSE:GRAPHITE-EQ',
    'NSE:GRASIM-EQ',
    'NSE:GRINDWELL-EQ',
    'NSE:GRSE-EQ',
    'NSE:GSFC-EQ',
    'NSE:GSPL-EQ',
    'NSE:GUJGASLTD-EQ',
    'NSE:HAL-EQ',
    'NSE:HAPPSTMNDS-EQ',
    'NSE:HATSUN-EQ',
    'NSE:HAVELLS-EQ',
    'NSE:HBLPOWER-EQ',
    'NSE:HCLTECH-EQ',
    'NSE:HDFCAMC-EQ',
    'NSE:HDFCBANK-EQ',
    'NSE:HDFCLIFE-EQ',
    'NSE:HEG-EQ',
    'NSE:HEROMOTOCO-EQ',
    'NSE:HFCL-EQ',
    'NSE:HGS-EQ',
    'NSE:HINDALCO-EQ',
    'NSE:HINDCOPPER-EQ',
    'NSE:HINDPETRO-EQ',
    'NSE:HINDUNILVR-EQ',
    'NSE:HINDZINC-EQ',
    'NSE:HLEGLAS-EQ',
    'NSE:HONAUT-EQ',
    'NSE:HUDCO-EQ',
    'NSE:ICICIBANK-EQ',
    'NSE:ICICIGI-EQ',
    'NSE:ICICIPRULI-EQ',
    'NSE:IDBI-EQ',
    'NSE:IDEA-EQ',
    'NSE:IDFC-EQ',
    'NSE:IDFCFIRSTB-EQ',
    'NSE:IEX-EQ',
    'NSE:IGL-EQ',
    'NSE:IIFL-EQ',
    'NSE:IIFLSEC-EQ',
    'NSE:INDHOTEL-EQ',
    'NSE:INDIAMART-EQ',
    'NSE:INDIANB-EQ',
    'NSE:INDIGO-EQ',
    'NSE:INDIGOPNTS-EQ',
    'NSE:INDOCO-EQ',
    'NSE:INDUSINDBK-EQ',
    'NSE:INDUSTOWER-EQ',
    'NSE:INFIBEAM-EQ',
    'NSE:INFY-EQ',
    'NSE:INGERRAND-EQ',
    'NSE:INOXGREEN-EQ',
    'NSE:INOXWIND-EQ',
    'NSE:INTELLECT-EQ',
    'NSE:IOB-EQ',
    'NSE:IOC-EQ',
    'NSE:IPCALAB-EQ',
    'NSE:IRB-EQ',
    'NSE:IRCTC-EQ',
    'NSE:IRFC-EQ',
    'NSE:ISEC-EQ',
    'NSE:ITC-EQ',
    'NSE:ITI-EQ',
    'NSE:JAMNAAUTO-EQ',
    'NSE:JBCHEPHARM-EQ',
    'NSE:JCHAC-EQ',
    'NSE:JINDALSAW-EQ',
    'NSE:JINDALSTEL-EQ',
    'NSE:JIOFIN-EQ',
    'NSE:JKCEMENT-EQ',
    'NSE:JKIL-EQ',
    'NSE:JKLAKSHMI-EQ',
    'NSE:JKPAPER-EQ',
    'NSE:JSL-EQ',
    'NSE:JSWENERGY-EQ',
    'NSE:JSWINFRA-EQ',
    'NSE:JSWSTEEL-EQ',
    'NSE:JTEKTINDIA-EQ',
    'NSE:JUBLFOOD-EQ',
    'NSE:JUBLPHARMA-EQ',
    'NSE:JUSTDIAL-EQ',
    'NSE:KALYANKJIL-EQ',
    'NSE:KANSAINER-EQ',
    'NSE:KARURVYSYA-EQ',
    'NSE:KAYNES-EQ',
    'NSE:KEC-EQ',
    'NSE:KIMS-EQ',
    'NSE:KIRLOSENG-EQ',
    'NSE:KIRLOSIND-EQ',
    'NSE:KNRCON-EQ',
    'NSE:KOLTEPATIL-EQ',
    'NSE:KOPRAN-EQ',
    'NSE:KOTAKBANK-EQ',
    'NSE:KPIGREEN-EQ',
    'NSE:KPITTECH-EQ',
    'NSE:KPRMILL-EQ',
    'NSE:KRBL-EQ',
    'NSE:KSB-EQ',
    'NSE:LALPATHLAB-EQ',
    'NSE:LAOPALA-EQ',
    'NSE:LAURUSLABS-EQ',
    'NSE:LAXMIMACH-EQ',
    'NSE:LEMONTREE-EQ',
    'NSE:LICHSGFIN-EQ',
    'NSE:LICI-EQ',
    'NSE:LINC-EQ',
    'NSE:LODHA-EQ',
    'NSE:LT-EQ',
    'NSE:LTF-EQ',
    'NSE:LTIM-EQ',
    'NSE:LTTS-EQ',
    'NSE:LUMAXIND-EQ',
    'NSE:LUMAXTECH-EQ',
    'NSE:LUPIN-EQ',
    'NSE:M-M-EQ',
    'NSE:M-MFIN-EQ',
    'NSE:MAHABANK-EQ',
    'NSE:MAHSCOOTER-EQ',
    'NSE:MANINDS-EQ',
    'NSE:MANKIND-EQ',
    'NSE:MAPMYINDIA-EQ',
    'NSE:MARATHON-EQ',
    'NSE:MARICO-EQ',
    'NSE:MARKSANS-EQ',
    'NSE:MARUTI-EQ',
    'NSE:MASFIN-EQ',
    'NSE:MASTEK-EQ',
    'NSE:MAXHEALTH-EQ',
    'NSE:MAZDOCK-EQ',
    'NSE:MEDANTA-EQ',
    'NSE:MFSL-EQ',
    'NSE:MIDCPNIFTY-INDEX',
    'NSE:MOIL-EQ',
    'NSE:MOREPENLAB-EQ',
    'NSE:MOTHERSON-EQ',
    'NSE:MPHASIS-EQ',
    'NSE:MRF-EQ',
    'NSE:MRPL-EQ',
    'NSE:MUTHOOTFIN-EQ',
    'NSE:NATCOPHARM-EQ',
    'NSE:NAUKRI-EQ',
    'NSE:NAZARA-EQ',
    'NSE:NBCC-EQ',
    'NSE:NCC-EQ',
    'NSE:NDTV-EQ',
    'NSE:NESCO-EQ',
    'NSE:NESTLEIND-EQ',
    'NSE:NETWORK18-EQ',
    'NSE:NEULANDLAB-EQ',
    'NSE:NHPC-EQ',
    'NSE:NIFTY50-INDEX',
    'NSE:NIFTYBANK-INDEX',
    'NSE:NIFTYINFRA-INDEX',
    'NSE:NIFTYIT-INDEX',
    'NSE:NLCINDIA-EQ',
    'NSE:NMDC-EQ',
    'NSE:NTPC-EQ',
    'NSE:NUVOCO-EQ',
    'NSE:NYKAA-EQ',
    'NSE:OBEROIRLTY-EQ',
    'NSE:OCCL-EQ',
    'NSE:OFSS-EQ',
    'NSE:OIL-EQ',
    'NSE:ONGC-EQ',
    'NSE:ONMOBILE-EQ',
    'NSE:ORIENTELEC-EQ',
    'NSE:ORIENTPPR-EQ',
    'NSE:PAGEIND-EQ',
    'NSE:PARADEEP-EQ',
    'NSE:PATANJALI-EQ',
    'NSE:PAYTM-EQ',
    'NSE:PEL-EQ',
    'NSE:PERSISTENT-EQ',
    'NSE:PETRONET-EQ',
    'NSE:PFC-EQ',
    'NSE:PGHH-EQ',
    'NSE:PIDILITIND-EQ',
    'NSE:PIIND-EQ',
    'NSE:PNB-EQ',
    'NSE:PNCINFRA-EQ',
    'NSE:POLICYBZR-EQ',
    'NSE:POLYCAB-EQ',
    'NSE:POONAWALLA-EQ',
    'NSE:POWERGRID-EQ',
    'NSE:PRAJIND-EQ',
    'NSE:PRESTIGE-EQ',
    'NSE:PRINCEPIPE-EQ',
    'NSE:PRSMJOHNSN-EQ',
    'NSE:PSB-EQ',
    'NSE:QUESS-EQ',
    'NSE:RADICO-EQ',
    'NSE:RAIN-EQ',
    'NSE:RAJESHEXPO-EQ',
    'NSE:RALLIS-EQ',
    'NSE:RAMCOSYS-EQ',
    'NSE:RATNAMANI-EQ',
    'NSE:RAYMOND-EQ',
    'NSE:RBLBANK-EQ',
    'NSE:RCF-EQ',
    'NSE:RECLTD-EQ',
    'NSE:RELAXO-EQ',
    'NSE:RELIANCE-EQ',
    'NSE:ROSSARI-EQ',
    'NSE:RVNL-EQ',
    'NSE:SAFARI-EQ',
    'NSE:SAIL-EQ',
    'NSE:SANOFI-EQ',
    'NSE:SBICARD-EQ',
    'NSE:SBILIFE-EQ',
    'NSE:SBIN-EQ',
    'NSE:SHOPERSTOP-EQ',
    'NSE:SHREECEM-EQ',
    'NSE:SHRIRAMFIN-EQ',
    'NSE:SIEMENS-EQ',
    'NSE:SJVN-EQ',
    'NSE:SOBHA-EQ',
    'NSE:SONACOMS-EQ',
    'NSE:SRF-EQ',
    'NSE:SUNDRMFAST-EQ',
    'NSE:SUNPHARMA-EQ',
    'NSE:SUNTV-EQ',
    'NSE:SUPRAJIT-EQ',
    'NSE:SUPREMEIND-EQ',
    'NSE:SUTLEJTEX-EQ',
    'NSE:SUZLON-EQ',
    'NSE:SYNGENE-EQ',
    'NSE:TATACHEM-EQ',
    'NSE:TATACOMM-EQ',
    'NSE:TATACONSUM-EQ',
    'NSE:TATAELXSI-EQ',
    'NSE:TATAMOTORS-EQ',
    'NSE:TATAMTRDVR-EQ',
    'NSE:TATAPOWER-EQ',
    'NSE:TATASTEEL-EQ',
    'NSE:TATATECH-EQ',
    'NSE:TCS-EQ',
    'NSE:TEAMLEASE-EQ',
    'NSE:TECHM-EQ',
    'NSE:THANGAMAYL-EQ',
    'NSE:THERMAX-EQ',
    'NSE:TIINDIA-EQ',
    'NSE:TITAN-EQ',
    'NSE:TORNTPHARM-EQ',
    'NSE:TORNTPOWER-EQ',
    'NSE:TRENT-EQ',
    'NSE:TRIVENI-EQ',
    'NSE:TTML-EQ',
    'NSE:TV18BRDCST-EQ',
    'NSE:TVSMOTOR-EQ',
    'NSE:UBL-EQ',
    'NSE:UCOBANK-EQ',
    'NSE:ULTRACEMCO-EQ',
    'NSE:UNIONBANK-EQ',
    'NSE:UNITDSPR-EQ',
    'NSE:UPL-EQ',
    'NSE:UTIAMC-EQ',
    'NSE:VAIBHAVGBL-EQ',
    'NSE:VARROC-EQ',
    'NSE:VBL-EQ',
    'NSE:VEDL-EQ',
    'NSE:VIPIND-EQ',
    'NSE:VOLTAS-EQ',
    'NSE:WELCORP-EQ',
    'NSE:WHIRLPOOL-EQ',
    'NSE:WIPRO-EQ',
    'NSE:WOCKPHARMA-EQ',
    'NSE:YESBANK-EQ',
    'NSE:ZEEL-EQ',
    'NSE:ZOMATO-EQ',
    'NSE:ZYDUSLIFE-EQ',
    'NSE:ZYDUSWELL-EQ',
    'BSE:SENSEX-INDEX'
]

# Database configuration
db_config = {
    'host': '118.139.182.3',
    'user': 'sqluser1',
    'password': 'TGDp0U&[1Y4S',
    'database': 'stocks'
}

# Connect to MySQL database
con = mysql.connector.connect(**db_config)
cur = con.cursor()

# Define date for data fetching as today
today = datetime.now().strftime('%Y-%m-%d')

# Loop through each stock symbol and fetch data
for line in lines:
    try:
        line = line.strip()
        data = {
            "symbol": line,
            "resolution": "5",
            "date_format": "1",
            "range_from": today,
            "range_to": today,
            "cont_flag": "1"
        }

        # Fetching historical data from Fyers API
        df = fyers.history(data=data)
        df = pd.DataFrame(df['candles'])
        df.columns = ['date', 'open', 'high', 'low', 'close', 'volume']
        df['date'] = pd.to_datetime(df['date'], unit='s')
        df['date'] = df['date'].dt.tz_localize(
            'UTC').dt.tz_convert('Asia/Kolkata')
        df['date'] = df['date'].dt.tz_localize(None)

        # Sorting and removing duplicates
        df_sorted = df.sort_values(by=['date'], ascending=True)
        df = df_sorted.drop_duplicates(subset='date', keep='first')
        df.reset_index(drop=True, inplace=True)

        # Prepare table name from stock symbol
        parts = line.split(':')[-1].replace('-', '_').replace('&', '_')
        table_name = parts.lower()

        # Insert data into database
        for _, row in df.iterrows():
            query = f"""
                INSERT IGNORE INTO {table_name} 
                VALUES ('{row['date']}', {row['open']}, {row['high']}, {row['low']}, {row['close']}, {row['volume']})
            """
            cur.execute(query)

        con.commit()
        print(f"Database for {table_name.upper()} updated successfully.")

    except Exception as e:
        # Print error message and skip to the next stock
        print(
            f"Error fetching data for {line}: {str(e)}. Skipping to next stock...")

# Close database connection
con.close()
